### ISSUE TITLE
splash state: player should not be in paused state

### ISSUE THREAD

**Issue by foliovision** [foliovision/freedom-video-player#262]
Original issue link: [#312 splash state: player should not be in paused state](https://github.com/flowplayer/flowplayer/issues/312)

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Apr 1, 2013

A player which is not loaded cannot be paused, so logically it doesn't make sense.

In practice: one cannot do for instance:

``` css
.is-paused.flowplayer .fp-ui {
  background-image: none;
}
```

to hide the on-screen play button in paused - but not in splash! - state.

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/265438?v=4' /> [nnarhinen](https://github.com/nnarhinen) commented on May 22, 2013

Not going to change this, workaround:

``` css
.flowplayer.is-splash.is-paused .fp-ui { display: inline-block; }
.flowplayer.is-paused .fp-ui { display: none; }
```

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on May 22, 2013

It's obviously not that easy.

``` css
.flowplayer.is-splash.is-paused .fp-ui { background-image: url(//releases.flowplayer.org/5.4.1/skin/img/play_white.png); }                                                                                                                
.flowplayer.is-paused .fp-ui { background-image: none; }
```

and the first rule needs to extended with the retina pix. But, yeah, ok ;-)
