### ISSUE TITLE
fp-waiting loading animation only visible on hover

### ISSUE THREAD

**Issue by foliovision** [foliovision/freedom-video-player#852]
Original issue link: [#1218 fp-waiting loading animation only visible on hover](https://github.com/flowplayer/flowplayer/issues/1218)

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Jul 17, 2017

The loading animation should be visible independently of whether the user hovers over the player area or not.
As this can be fixed by:
```css
.flowplayer.is-loading .fp-waiting, .flowplayer.is-seeking .fp-waiting {
  display: block !important; /* !important flag added
}
```
this looks a lot like a simple oversight.

See: https://flowplayer.com/forum/#!/skinning_css:player-doesnt-show-waiting

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/1395672?v=4' /> [bbbo](https://github.com/bbbo) commented on Jun 4, 2018

@nnarhinen this doesn't seem to be fixed (or a regression) in 7.2.6.:

http://www.manicmovies.com/watch.php?id=347#.WxVuNJ_7SiN

shows loading animation only when hovering

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/265438?v=4' /> [nnarhinen](https://github.com/nnarhinen) commented on Jun 18, 2018

Please don't re-open issues. It messes up the milestoning.
