### ISSUE TITLE
Fullscreen: hide cursor on mouseout

### ISSUE THREAD

**Issue by foliovision** [foliovision/freedom-video-player#855]
Original issue link: [#1223 Fullscreen: hide cursor on mouseout](https://github.com/flowplayer/flowplayer/issues/1223)

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Jul 27, 2017

The cursor can be felt as very distracting in fullscreen; see e.g. https://flowplayer.com/forum/#!/setup:how-hidden-cursor-in-fullsc

I propose:
```css
.flowplayer.is-fullscreen.is-mouseout .fp-ui {
  cursor: none;
}
```
which seems to work fine in tests so far.

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/168338?v=4' /> [phloxic](https://github.com/phloxic) commented on Jul 27, 2017

Or, as controls are shown in paused state, for consistency:
```css
.flowplayer.is-fullscreen.is-mouseout.is-playing .fp-ui {
  cursor: none;
}
```

----

<img width='32' height='32' src='https://avatars.githubusercontent.com/u/265438?v=4' /> [nnarhinen](https://github.com/nnarhinen) commented on Aug 7, 2017

The fix most likely is not 100% cross-browser compatible but still better than original.
